(()=>{
const dialog=document.querySelector('#floorplan-modal');if(!dialog)return;
const $=s=>dialog.querySelector(s),svg=$('#fp-camera'),ns='http://www.w3.org/2000/svg',reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const config={'r1-78':{name:'Dunes · R1-78',type:'C3',area:245,height:1555},'r5-46':{name:'Acacia · R5-46',type:'C6',area:246,height:1494}};
const cache=new Map();let unit='r1-78',rooms=[],frame,loadVersion=0,opener=null,previousOverflow='';
function camera(target){cancelAnimationFrame(frame);const start=svg.getAttribute('viewBox').split(/\s+/).map(Number),t0=performance.now();function tick(t){const p=reduced?1:Math.min(1,(t-t0)/800),e=1-Math.pow(1-p,4);svg.setAttribute('viewBox',target.map((v,i)=>start[i]+(v-start[i])*e).join(' '));if(p<1)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick)}
function fullPlan(animate=true){const c=config[unit];if(animate)camera([0,0,1287,c.height]);else{cancelAnimationFrame(frame);svg.setAttribute('viewBox',`0 0 1287 ${c.height}`)}dialog.querySelectorAll('.fp-room').forEach(e=>e.setAttribute('aria-pressed','false'));$('#fp-room-select').value='';$('#fp-kicker').textContent=`VILLA ${c.type} / GROUND FLOOR`;$('#fp-room-name').textContent='Make yourself at home.';$('#fp-room-size').textContent=`4 bedrooms · ${c.area} sqm BUA`;$('#fp-room-description').textContent='Tap a room on the plan, or choose a space below to see its dimensions.';}
function selectRoom(i){const r=rooms[i];if(!r)return;const c=config[unit],[x,y,rw,rh]=r[3],w=Math.max(500,rw+180),h=w*c.height/1287;camera([Math.max(0,Math.min(1287-w,x+rw/2-w/2)),Math.max(0,Math.min(c.height-h,y+rh/2-h/2)),w,h]);dialog.querySelectorAll('.fp-room').forEach((el,n)=>el.setAttribute('aria-pressed',String(n===i)));$('#fp-room-select').value=String(i);$('#fp-kicker').textContent=`${String(i+1).padStart(2,'0')} / VILLA ${c.type}`;$('#fp-room-name').textContent=r[0];$('#fp-room-size').textContent=r[1];$('#fp-room-description').textContent=r[2];}
function drawRooms(){const group=$('#fp-rooms');group.replaceChildren();const select=$('#fp-room-select');select.replaceChildren(new Option('Choose a room',''));rooms.forEach((r,i)=>{const [x,y,w,h]=r[3],g=document.createElementNS(ns,'g'),rect=document.createElementNS(ns,'rect'),circle=document.createElementNS(ns,'circle'),label=document.createElementNS(ns,'text');Object.entries({class:'fp-room',role:'button',tabindex:0,'aria-label':`${r[0]}, ${r[1]}. Show room dimensions`,'aria-pressed':'false'}).forEach(([k,v])=>g.setAttribute(k,v));Object.entries({x,y,width:w,height:h,rx:4}).forEach(([k,v])=>rect.setAttribute(k,v));Object.entries({cx:x+w/2,cy:y+h/2,r:25}).forEach(([k,v])=>circle.setAttribute(k,v));label.setAttribute('x',x+w/2);label.setAttribute('y',y+h/2);label.textContent=String(i+1);g.append(rect,circle,label);g.addEventListener('click',()=>selectRoom(i));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectRoom(i)}});group.append(g);select.add(new Option(`${i+1}. ${r[0]}`,String(i)))});}
async function loadUnit(id){unit=id;const version=++loadVersion,c=config[id];rooms=[];$('#fp-rooms').replaceChildren();$('#fp-room-select').replaceChildren(new Option('Loading rooms…',''));$('#fp-room-select').disabled=true;$('#fp-load-status').textContent='Loading room details…';$('#fp-retry').hidden=true;$('#floorplan-modal-title').textContent=c.name;$('#fp-image').setAttribute('href',`${id}/assets/floor.jpg`);$('#fp-image').setAttribute('height',c.height);svg.setAttribute('aria-label',`${c.name} interactive floor plan`);$('#fp-original').href=`${id}/assets/plan-detail.jpg`;dialog.querySelectorAll('[data-floorplan-switch]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.floorplanSwitch===id)));fullPlan(false);$('.fp-content').scrollTop=0;
try{if(!cache.has(id))cache.set(id,fetch(`${id}/rooms.json`).then(r=>{if(!r.ok)throw Error('Room details unavailable');return r.json()}).catch(e=>{cache.delete(id);throw e}));const data=await cache.get(id);if(version!==loadVersion||!dialog.open)return;rooms=data;drawRooms();$('#fp-room-select').disabled=false;$('#fp-load-status').textContent='';}catch(e){if(version!==loadVersion||!dialog.open)return;$('#fp-load-status').textContent='Room details could not load. You can retry or open the original plan.';$('#fp-retry').hidden=false;}}
function open(id,trigger){if(!config[id])return;opener=trigger;if(!dialog.open){previousOverflow=document.body.style.overflow;dialog.showModal();document.body.style.overflow='hidden'}loadUnit(id);$('#fp-close').focus();}
document.querySelectorAll('[data-open-floorplan]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.openFloorplan,b)));dialog.querySelectorAll('[data-floorplan-switch]').forEach(b=>b.addEventListener('click',()=>loadUnit(b.dataset.floorplanSwitch)));$('#fp-room-select').addEventListener('change',e=>e.target.value===''?fullPlan():selectRoom(Number(e.target.value)));$('#fp-reset').addEventListener('click',()=>fullPlan());$('#fp-retry').addEventListener('click',()=>loadUnit(unit));$('#fp-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{++loadVersion;cancelAnimationFrame(frame);document.body.style.overflow=previousOverflow;opener?.focus({preventScroll:true})});dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close()});
})();
